// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFutbolistasSeg;

#nullable disable

namespace WebApiFutbolistasSeg.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220501191702_FutbolistaEquipo")]
    partial class FutbolistaEquipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.Futbolista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Futbolistas");
                });

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.FutbolistaEquipo", b =>
                {
                    b.Property<int>("FutbolistaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("FutbolistaId", "EquipoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("FutbolistaEquipo");
                });

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.FutbolistaEquipo", b =>
                {
                    b.HasOne("WebApiFutbolistasSeg.Entidades.Equipo", "Equipo")
                        .WithMany("FutbolistaEquipo")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiFutbolistasSeg.Entidades.Futbolista", "Futbolista")
                        .WithMany("FutbolistaEquipo")
                        .HasForeignKey("FutbolistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Futbolista");
                });

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.Equipo", b =>
                {
                    b.Navigation("FutbolistaEquipo");
                });

            modelBuilder.Entity("WebApiFutbolistasSeg.Entidades.Futbolista", b =>
                {
                    b.Navigation("FutbolistaEquipo");
                });
#pragma warning restore 612, 618
        }
    }
}
